name: "install uv"
description: "Install uv using the community action"
runs:
    using: composite
    steps:
        - name: install uv
          uses: astral-sh/setup-uv@v3
          with:
              version: "latest"
