name: "Type checking"
description: "Type checking using the community action"
runs:
    using: composite
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup environment
          uses: ./.github/actions/setup

        - name: Type checking
          run: uv run pyright .
          shell: bash
