name: Python Code Quality
on: [push]
jobs:
    lock_file:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uv lock --locked
    linting:
        runs-on: ubuntu-latest
        needs: [lock_file]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uvx ruff check .
    formatting:
        runs-on: ubuntu-latest
        needs: [lock_file]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uvx ruff format .
            - run: uvx ruff format --check .
    tests:
        runs-on: ubuntu-latest
        needs: [lock_file]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uv run pytest -v --durations=0
    build:
        runs-on: ubuntu-latest
        needs: [lock_file, linting, formatting, tests]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - run: uv build